import defaultTheme from '../themes';

const typographyTheme = {
  defaultSize: 13,
  defaultColor: defaultTheme.colors.riverBedDark,
  h1SizeLarge: 30,
  h1SizeLargeMarginTop: 24,
  h1SizeLargeMarginBottom: 18,
  h1SizeMedium: 24,
  h1SizeMediumMarginTop: 18,
  h1SizeMediumMarginBottom: 12,
  h1SizeSmall: 18,
  h1SizeSmallMarginTop: 12,
  h1SizeSmallMarginBottom: 8,
  h2SizeLarge: 24,
  h2SizeLargeMarginTop: 18,
  h2SizeLargeMarginBottom: 14,
  h2SizeMedium: 20,
  h2SizeMediumMarginTop: 14,
  h2SizeMediumMarginBottom: 10,
  h2SizeSmall: 16,
  h2SizeSmallMarginTop: 10,
  h2SizeSmallMarginBottom: 8,
  h3SizeLarge: 20,
  h3SizeLargeMarginTop: 16,
  h3SizeLargeMarginBottom: 12,
  h3SizeMedium: 18,
  h3SizeMediumMarginTop: 14,
  h3SizeMediumMarginBottom: 10,
  h3SizeSmall: 14,
  h3SizeSmallMarginTop: 12,
  h3SizeSmallMarginBottom: 8,
  h4SizeLarge: 16,
  h4SizeLargeMarginTop: 16,
  h4SizeLargeMarginBottom: 12,
  h4SizeMedium: 14,
  h4SizeMediumMarginTop: 14,
  h4SizeMediumMarginBottom: 10,
  h4SizeSmall: 12,
  h4SizeSmallMarginTop: 10,
  h4SizeSmallMarginBottom: 8,
  h5SizeLarge: 14,
  h5SizeLargeMarginTop: 14,
  h5SizeLargeMarginBottom: 12,
  h5SizeMedium: 12,
  h5SizeMediumMarginTop: 12,
  h5SizeMediumMarginBottom: 10,
  h5SizeSmall: 10,
  h5SizeSmallMarginTop: 10,
  h5SizeSmallMarginBottom: 8,
  h6SizeLarge: 12,
  h6SizeLargeMarginTop: 12,
  h6SizeLargeMarginBottom: 12,
  h6SizeMedium: 10,
  h6SizeMediumMarginTop: 10,
  h6SizeMediumMarginBottom: 10,
  h6SizeSmall: 10,
  h6SizeSmallMarginTop: 10,
  h6SizeSmallMarginBottom: 10,
  lineHeightRatio: 1.75,
  headingLineHeightRatio: 1.68,
  sizes: defaultTheme.sizes,
  colors: defaultTheme.colors,
};

export default typographyTheme;
